version: '3.6'

services:

  main:
    image: 'jenkins'
    build:
      context: .
    ports:
      - 8080:8080
      - 50000:50000
    secrets:
      - jenkins-user
      - jenkins-pass

secrets:
  jenkins-user:
    file: ./secret.txt
  jenkins-pass:
    file: ./secret.txt